# Generated by Django 4.2.7 on 2023-11-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='posx',
            field=models.CharField(default=0, help_text='float position', max_length=7),
        ),
        migrations.AddField(
            model_name='shape',
            name='posy',
            field=models.CharField(default=0, help_text='float position', max_length=7),
        ),
        migrations.AlterField(
            model_name='shape',
            name='type',
            field=models.CharField(choices=[('1', 'Border'), ('2', 'User'), ('3', 'Ball')], max_length=1),
        ),
    ]
