# Generated by Django 4.2.7 on 2023-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_shape_posx_shape_posy_alter_shape_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbPlayer', models.CharField(help_text='number of users', max_length=3)),
                ('listOfPlayer', models.CharField(help_text='list of player in json and if they are ready in json')),
                ('duringTime', models.CharField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
