# Generated by Django 4.2.7 on 2023-11-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_mapsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='duringTime',
            field=models.CharField(default=0, help_text='time of the party'),
        ),
    ]
