# Generated by Django 4.2.7 on 2023-12-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_mapsettings_duringtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='listOfPlayer',
            field=models.CharField(default=0, help_text='list of player in json and if they are ready in json'),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='nbPlayer',
            field=models.CharField(default=2, help_text='number of users', max_length=3),
        ),
    ]
