# Generated by Django 4.2.7 on 2023-12-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_mapsettings_listofplayer_and_more'),
    ]

    operations = [
    ]
