# Generated by Django 4.2.7 on 2023-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_mapsettings_listofplayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='listOfPlayer',
            field=models.CharField(default='[]', help_text='list of player in json and if they are ready in json'),
        ),
    ]
