# Generated by Django 4.2.7 on 2023-12-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_mapsettings_listofplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='party_id',
            field=models.CharField(default=-1, help_text='id of the party', max_length=3),
        ),
        migrations.AlterField(
            model_name='mapsettings',
            name='listOfPlayer',
            field=models.CharField(default='', help_text='list of player in json and if they are ready in json'),
        ),
    ]
