# Generated by Django 4.2.7 on 2023-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_shape_party_id_alter_mapsettings_listofplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='item_id',
            field=models.CharField(default=-1, help_text='id of the item', max_length=3),
        ),
    ]
