# Generated by Django 4.2.7 on 2023-12-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_shape_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='item_id',
            field=models.CharField(default=-1, help_text='id of the item', max_length=7),
        ),
        migrations.AlterField(
            model_name='shape',
            name='party_id',
            field=models.CharField(default=-1, help_text='id of the party', max_length=7),
        ),
    ]
