# Generated by Django 4.2.7 on 2023-12-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_merge_20231204_1528'),
        ('game', '0009_alter_shape_item_id_alter_shape_party_id'),
    ]

    operations = [
    ]
