# Generated by Django 4.2.8 on 2023-12-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_merge_20231204_1531'),
        ('game', '0010_merge_20231204_1612'),
    ]

    operations = [
    ]
