# Generated by Django 4.2.8 on 2023-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_merge_20231209_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsettings',
            name='listOfPlayer',
            field=models.CharField(default='', help_text='list of player in json and if they are ready in json'),
        ),
    ]
