# Generated by Django 4.2.11 on 2024-03-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_mapsettings_listofplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shape',
        ),
        migrations.RemoveField(
            model_name='mapsettings',
            name='nbPlayer',
        ),
    ]
