# Generated by Django 4.2.10 on 2024-03-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='A rage-filled warrior, wielding a wicked blade, with lightning-fast reflexes and unmatched strength, charges into battle with unpredictable fury.<eos>'),
        ),
    ]
