# Generated by Django 4.2.10 on 2024-03-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='A warrior adorned with flowing red hair and piercing blue eyes, wields a glowing sword forged in the fires of legend, defending the realm against the forces of darkness.'),
        ),
    ]
