# Generated by Django 4.2.10 on 2024-03-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='A powerful warrior with high physical strength and agility, adept at close-up combat with a signature finishing move: a devastating single-target jump attack.'),
        ),
    ]
