# Generated by Django 4.2.10 on 2024-03-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='A fierce warrior with deadly martial arts skills and agile movement, capable of wielding elemental powers to defeat his enemies.'),
        ),
    ]
