# Generated by Django 4.2.11 on 2024-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='A stoic warrior, wielding brute force and agile movement, battles with skilled precision, striking down enemies with devastating physical attacks and powerful elemental magic.'),
        ),
    ]
