# Generated by Django 4.2.11 on 2024-03-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='A fierce warrior with a devastating arsenal of close-up attacks and debilitating strikes, specializing in brutal, quick, and deadly close-up combat.'),
        ),
    ]
