# Generated by Django 4.2.11 on 2024-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='A master of martial arts and wielding a powerful weapon, Warrior is a hero who specializes in close-up combat and raw power.'),
        ),
    ]
