# Generated by Django 4.2.11 on 2024-03-12 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocklist',
            field=models.ManyToManyField(blank=True, related_name='blocklist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='A master of martial arts, a warrior of unmatched strength and speed, specializing in close-up combat with devastating strikes and lightning-fast parries.'),
        ),
    ]
