# Generated by Django 4.2.11 on 2024-03-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Ironclad Sentinel: A towering behemoth clad in impenetrable armor, impervious to all attacks.'),
        ),
    ]
