# Generated by Django 4.2.11 on 2024-03-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Stormbringer: A tempestuous warrior harnessing the power of lightning, striking fear into foes.'),
        ),
    ]
