# Generated by Django 4.2.9 on 2024-02-06 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0003_alter_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(limit_choices_to={'room__isnull': True}, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
