# Generated by Django 4.2.10 on 2024-02-08 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0007_alter_room_name_alter_room_slug_alter_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
