# Generated by Django 4.2.10 on 2024-02-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_alter_room_name_alter_room_slug_alter_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='test1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='test2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
